language: python
python:
  - "2.7"

env:
  global:
    - SECRET_KEY=blajblajbasdf
  matrix:
    - DJANGO=1.8

install:
  - pip install -r requirements.txt

script: python manage.py test

notifications:
  email:
    on_success: change
    on_failure: change
